bundler_args: --without development
language: ruby
only:
  - master
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
rvm:
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
