before_script:
  - mysql -e 'create database delayed_job_test;'
  - psql -c 'create database delayed_job_test;' -U postgres
bundler_args: --without development
env:
  - "CI_DB_ADAPTER=sqlite3"
  - "CI_DB_ADAPTER=mysql"
  - "CI_DB_ADAPTER=postgresql"
language: ruby
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
rvm:
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - 1.8.7
  - 1.9.3
  - 2.0.0
